language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'grunt build'
deploy:
  provider: s3
  access_key_id: "AKIAJFRWTT77P6RNBYVA"
  secret_access_key: "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"
  bucket: "www.mikenewlin.net"  
  skip_cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/dist
  endpoint: "www.mikenewlin.net.s3-website-us-west-2.amazonaws.com"
  region: "us-west-2"
notifications:
  hipchat:
    rooms:
      - d4e111c3aac8c2593fba3190df7dc4@677475
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'  
    on_success: always
    on_failure: always