language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
deploy:
  provider: s3
  access_key_id: "AKIAJFRWTT77P6RNBYVA"
  secret_access_key: "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"
  bucket: "www.mikenewlin.net"  
  skip_cleanup: true
  local-dir: $TRAVIS_BUILD_DIR/dist
  endpoint: "www.mikenewlin.net.s3-website-us-west-2.amazonaws.com"
  region: "us-west-2"

